package com.academic.adviser.constants;

public enum BigFiveTraitLevel {
    LOW_EXTROVERSION,
    HIGH_EXTROVERSION,
    LOW_CONSCIENTIOUSNESS,
    HIGH_CONSCIENTIOUSNESS,
    LOW_NEUROTICISM,
    HIGH_NEUROTICISM,
    LOW_OPENNESS,
    HIGH_OPENNESS,
    LOW_AGREEABLENESS,
    HIGH_AGREEABLENESS
}
