package bigFive;
import com.academic.adviser.drools.model.QuestionPair;
import com.academic.adviser.drools.model.CareerTest;
import com.academic.adviser.drools.model.CareerAreas;
import com.academic.adviser.model.CareerArea;

rule "Career QuestionPair_84"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 1 || id == 8) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(84) };
end

rule "Career QuestionPair_83"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 3 || id == 7) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(83) };
end

rule "Career QuestionPair_82"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 5 || id == 6) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(82) };
end

rule "Career QuestionPair_81"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 9 || id == 2) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(81) };
end

rule "Career QuestionPair_80"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 4 || id == 11) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(80) };
end

rule "Career QuestionPair_79"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 3 || id == 8) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(79) };
end

rule "Career QuestionPair_78"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 9 || id == 1) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(78) };
end

rule "Career QuestionPair_77"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 6 || id == 8) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(77) };
end

rule "Career QuestionPair_76"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 7 || id == 5) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(76) };
end

rule "Career QuestionPair_75"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 2 || id == 8) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(75) };
end

rule "Career QuestionPair_74"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 11 || id == 12) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(74) };
end

rule "Career QuestionPair_73"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 12 || id == 4) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(73) };
end

rule "Career QuestionPair_72"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 1 || id == 7) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(72) };
end

rule "Career QuestionPair_71"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 9 || id == 3) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(71) };
end

rule "Career QuestionPair_70"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 3 || id == 12) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(70) };
end

rule "Career QuestionPair_69"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 7 || id == 2) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(69) };
end

rule "Career QuestionPair_68"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 5 || id == 8) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(68) };
end

rule "Career QuestionPair_67"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 4 || id == 10) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(67) };
end

rule "Career QuestionPair_66"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 12 || id == 1) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(66) };
end

rule "Career QuestionPair_65"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 12 || id == 10) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(65) };
end

rule "Career QuestionPair_64"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 6 || id == 7) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(64) };
end

rule "Career QuestionPair_63"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 12 || id == 2) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(63) };
end

rule "Career QuestionPair_62"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 5 || id == 9) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(62) };
end

rule "Career QuestionPair_61"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 12 || id == 7) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(61) };
end

rule "Career QuestionPair_60"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 1 || id == 11) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(60) };
end

rule "Career QuestionPair_59"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 12 || id == 9) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(59) };
end

rule "Career QuestionPair_58"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 10 || id == 5) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(58) };
end

rule "Career QuestionPair_57"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 2 || id == 11) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(57) };
end

rule "Career QuestionPair_56"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 9 || id == 6) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(56) };
end

rule "Career QuestionPair_55"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 11 || id == 3) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(55) };
end

rule "Career QuestionPair_54"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 8 || id == 1) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(54) };
end

rule "Career QuestionPair_53"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 9 || id == 11) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(53) };
end

rule "Career QuestionPair_52"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 10 || id == 2) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(52) };
end

rule "Career QuestionPair_51"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 6 || id == 11) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(51) };
end

rule "Career QuestionPair_50"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 5 || id == 11) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(50) };
end

rule "Career QuestionPair_49"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 3 || id == 10) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(49) };
end

rule "Career QuestionPair_48"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 1 || id == 9) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(48) };
end

rule "Career QuestionPair_47"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 10 || id == 6) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(47) };
end

rule "Career QuestionPair_46"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 11 || id == 10) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(46) };
end

rule "Career QuestionPair_45"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 2 || id == 9) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(45) };
end

rule "Career QuestionPair_44"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 4 || id == 12) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(44) };
end

rule "Career QuestionPair_43"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 9 || id == 3) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(43) };
end

rule "Career QuestionPair_42"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 10 || id == 1) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(42) };
end

rule "Career QuestionPair_41"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 12 || id == 5) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(41) };
end

rule "Career QuestionPair_40"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 7 || id == 11) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(40) };
end

rule "Career QuestionPair_39"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 8 || id == 2) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(39) };
end

rule "Career QuestionPair_38"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 11 || id == 4) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(38) };
end

rule "Career QuestionPair_37"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 5 || id == 12) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(37) };
end

rule "Career QuestionPair_36"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 1 || id == 7) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(36) };
end

rule "Career QuestionPair_35"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 3 || id == 8) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(35) };
end

rule "Career QuestionPair_34"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 12 || id == 6) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(34) };
end

rule "Career QuestionPair_33"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 4 || id == 10) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(33) };
end

rule "Career QuestionPair_32"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 2 || id == 7) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(32) };
end

rule "Career QuestionPair_31"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 7 || id == 3) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(31) };
end

rule "Career QuestionPair_30"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 6 || id == 1) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(30) };
end

rule "Career QuestionPair_29"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 12 || id == 8) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(29) };
end

rule "Career QuestionPair_28"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 5 || id == 11) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(28) };
end

rule "Career QuestionPair_27"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 9 || id == 4) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(27) };
end

rule "Career QuestionPair_26"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 3 || id == 6) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(26) };
end

rule "Career QuestionPair_25"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 6 || id == 2) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(25) };
end

rule "Career QuestionPair_24"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 7 || id == 10) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(24) };
end

rule "Career QuestionPair_23"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 5 || id == 10) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(23) };
end

rule "Career QuestionPair_22"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 10 || id == 9) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(22) };
end

rule "Career QuestionPair_21"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 8 || id == 4) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(21) };
end

rule "Career QuestionPair_20"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 5 || id == 3) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(20) };
end

rule "Career QuestionPair_19"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 6 || id == 10) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(19) };
end

rule "Career QuestionPair_18"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 5 || id == 1) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(18) };
end

rule "Career QuestionPair_17"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 11 || id == 6) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(17) };
end

rule "Career QuestionPair_16"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 4 || id == 7) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(16) };
end

rule "Career QuestionPair_15"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 2 || id == 5) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(15) };
end

rule "Career QuestionPair_14"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 3 || id == 4) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(14) };
end

rule "Career QuestionPair_13"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 7 || id == 9) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(13) };
end

rule "Career QuestionPair_12"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 1 || id == 4) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(12) };
end

rule "Career QuestionPair_11"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 8 || id == 10) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(11) };
end

rule "Career QuestionPair_10"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 6 || id == 12) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(10) };
end

rule "Career QuestionPair_9"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 4 || id == 2) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(9) };
end

rule "Career QuestionPair_8"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 8 || id == 9) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(8) };
end

rule "Career QuestionPair_7"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 6 || id == 4) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(7) };
end

rule "Career QuestionPair_6"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 3 || id == 1) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(6) };
end

rule "Career QuestionPair_5"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 11 || id == 8) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(5) };
end

rule "Career QuestionPair_4"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 7 || id == 8) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(4) };
end

rule "Career QuestionPair_3"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 2 || id == 3) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(3) };
end

rule "Career QuestionPair_2"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 4 || id == 5) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(2) };
end

rule "Career QuestionPair_1"
lock-on-active true
agenda-group "career-questions"
when
    $areas: CareerAreas($careerAreas: careerAreas)
    $test: CareerTest()
    Number($value: intValue > 0) from accumulate(
            CareerArea($area: this, id == 1 || id == 2) from $careerAreas,
            count($area)
        )
then
    modify ($test) { addPair(1) };
end


