INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Meni su žurke život.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Osećam malu zabrinutost za druge.', 'AGREEABLENESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Uvek sam spreman.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Lako se nasekiram.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam bogat vokabular.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ne pricam mnogo.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Zainteresovan sam za ljude.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ostavljam svoje stvari za sobom.', 'CONSCIENTIOUSNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Uglavnom sam opušten.', 'NEUROTICISM', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Sa teškoćom shvatam apstraktne ideje.', 'OPENNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Osećam se prijatno u društvu.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Vređam ljude.', 'AGREEABLENESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Vodim računa o detaljima.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Brinem u vezi stvari.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam bujnu maštu.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ne volim da se ističem.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Saosećam sa tuđim osećanjima.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Neuredan sam.', 'CONSCIENTIOUSNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Retko osećam melanholiju.', 'NEUROTICISM', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam zainteresovan za apstraktne ideje.', 'OPENNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Započinjem konverzaciju.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam zainteresovan za probleme drugih ljudi.', 'AGREEABLENESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Rešavam svoje obaveze na vreme. ', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Lako se uznemirim.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam odlične ideje.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam pričljive prirode.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam meko srce.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Često zaboravljam da vratim stvari na svoje mesto.', 'CONSCIENTIOUSNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Lako se iznerviram.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam naročito maštovit.', 'OPENNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Pričam sa mnogo različitih ljudi na žurci.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam zainteresovan za druge ljude.', 'AGREEABLENESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Volim red.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Često menjam raspoloženje.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Brzo shvatam stvari.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ne volim da privlačim pažnju na sebe.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Izdvajam vreme za druge.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Zabušavam.', 'CONSCIENTIOUSNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Brzo menjam raspoloženje.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Koristim komplikovane reči.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ne smeta mi kad sam u centru pažnje.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam osećaj empatije.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Pratim raspored.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Razdražljive sam prirode.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Periodično sagledavam stvari.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Tih sam u prisustvu nepoznatih ljudi.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Činim da se drugi ljudi osećaju opušteno.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Uživam u svom poslu.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Često se osećam melanholično.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Pun sam ideja.', 'OPENNESS', 'ADD');

-- career area
INSERT INTO CAREER_AREA(name, rang) VALUES ('Administracija', '90');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Bezbednost', '60');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Tehnika', '120');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Kreativnost', '110');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Kultura', '50');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Literatura', '70');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Nauka', '100');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Pomaganje', '30');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Poljoprivreda', '80');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Praktična delatnost', '20');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Sport', '40');
INSERT INTO CAREER_AREA(name, rang) VALUES ('Personalne usluge', '10');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('1', '3');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('1', '4');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('2', '3');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('2', '4');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('2', '8');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('3', '7');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('3', '5');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('4', '7');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('4', '9');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('4', '1');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('5', '3');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('5', '9');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('5', '1');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('6', '7');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('6', '4');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('6', '9');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('7', '7');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('7', '9');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('7', '3');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('8', '9');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('8', '1');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('8', '4');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('9', '4');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('9', '3');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('9', '1');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('10', '1');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('10', '9');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('11', '1');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('11', '9');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('11', '3');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('12', '1');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('12', '4');
INSERT INTO TRAITS(career_area_id, traits) VALUES ('12', '9');

-- professional orientation questions
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Kontrolisati dokumentaciju o finansijskom poslovanju preduzeća', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Obučavati ljude da koriste borbenu  opremu, vatrena oružja i oruđa', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Uređivati javne prostore (trgove, ulice i šetališta)', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pisati knjigu o istoriji umetnosti', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Kontrolisati ljude i vozila pri prelasku državne granice', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Instalirati programe za rad na računaru', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Vršiti istraživanja iz oblasti nuklearne fizike', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Podučavati decu kako da pravilno izgovaraju glasove', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Raditi u organizaciji svetskog sportskog prvenstva', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Raditi kao terapeut u zavodu za bolesti zavisnosti (za narkomane i alkoholičare)', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Izrađivati električne merne instrumente', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Voditi poslovne knjige neke firme', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Birati i uređivati članke za objavljivanje u dnevnim novinama', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Kreirati nove modele odeće', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Brinuti se o potrebama dece ometene u psihofizičkom razvoju', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Planirati i brinuti o ishrani stoke na farmi ili poljoprivrednom dobru', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Dizajnirati reklamne postere i bilborde', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Učestvovati u akcijama specijalne antiterorističke borbene jedinice', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Držati javna predavanja (građanima, studentima ili učenicima)', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Sastavljati jelovnik za svečani prijem', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pružati prvu medicinsku pomoć povređenim osobama', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Krečiti stan ili kuću', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Raditi na šalteru u banci ili pošti', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Uređivati unutrašnje prostore stambenih ili poslovnih objekata (enterijere)', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Vršiti naučna istraživanja', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Skladištiti voće i povrće u hladnjačama', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Testirati i popravljati računare', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Urediti scenografiju na filmu ili u pozorištu', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Obučavati vojnike strojevom koraku', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Organizovati umetničke izložbe', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Uređivati parkove i vrtove', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Proučavati poreklo, nastanak i sastav zemljine kore', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Nadzirati i ocenjivati sportske sudije', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Zastupati interese stranke, u svojstvu advokata, na sudu', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Učestvovati u organizaciji kulturnih događaja', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Praviti dijagram prihoda i rashoda u nekoj privrednoj organizaciji (firmi)', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pisati tekstove za pesme rok i pop muzike', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Popravljati kućne električne aparate', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Voditi umetničku galeriju', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Ispitivati elektrotehničke materijale', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Organizovati javne akcije prikupljanja pomoći za operacije obolelih osoba', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Projektovati reprezentativne zgrade (vile, pozorišta, pošte, železničke stanice)', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Popravljati motorna vozila', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Nadzirati izleganja pilića na farmi', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Baviti se filmskom kritikom', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Sklapati nameštaj od gotovih delova', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Izvoditi eksperimente iz oblasti organske hemije', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Uvoditi centralno grejanje u kuće i solitere', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Prevoditi knjige i tekstove na (i sa) stranih jezika', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Planirati borbenu obuku vojske, žandarmerije ili policije', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Otkrivati i otklanjati kvarove na televizijskim i radio aparatima', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Smišljati slogane za reklame', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Birati i prodavati voće', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Uređivati i ukrašavati izloge', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Baviti se umetničkom fotografijom', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Sklapati ugovore sa sportskim timovima i igračima', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Oblikovati moderne ženske i muške frizure', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Razgovarati sa ljudima o njihovim psihičkim problemima', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Čitati vesti na tv-u ili radiju', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Obračunavati platu uzimajući u obzir poreze, beneficije i takse', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Izvoditi eksperimente o ljudskom ponašanju u laboratoriji', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Crtati sheme električnih uređaja i aparata', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Vršiti uviđaj na mestu zločina', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Istraživati faktore rizika oboljevanja od srčanih bolesti', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Dizajnirati modernu kuhinju', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Popravljati kućne aparate i instalacije', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Organizovati zabavu ili proslavu u noćnom klubu', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pisati romane, pesme ili pripovetke', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Instalirati operativne računarske programe i sisteme', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pomagati ljudima koji imaju psihičke, telesne ili socijalne probleme', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Vršiti isplate i naplate novca u banci', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Izučavati lekovito bilje radi pronalaska novog leka', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Uređivati obrazovni program za decu', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Brinuti o kvalitetu usluživanja gostiju u restoranu', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Upravljati radom sportskog centra', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Kreirati pozorišne kostime', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Vaspitavati mlade ljude koji imaju problema s ponašanjem', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Obučavati posadu borbenog aviona ili broda', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Proučavati dejstvo lekova na ljudski organizam', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Organizovati sportsko takmičenje', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Usluživati i brinuti o putnicima na avionskom letu', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Proučavati nacionalnu muzičku istoriju', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Ručno izrađivati proizvode za domaćinstva', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Procenjivati vrednost uvezene robe i određivati visinu takse', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Gajiti domaće životinje', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pisati kompjuterske programe', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Dizajnirati sobne tapete', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Organizovati program boravka grupa u turističkom odmaralištu ili letovalištu', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Rasvetljavati krivična dela i privoditi pravdi njihove izvršioce', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Saditi i navodnjavati voće i povrće', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Ugovoriti prodaju (transfer) domaćih igrača stranim klubovima', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Popravljati puške i pištolje', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Postavljate zidne tapete', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Birati pesme za objavljivanje u literalnom časopisu', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Obračunavati visinu poreza za razne vrste robe', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Prskati voćnjak zaštitinim sredstvima', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Smišljati program za kurs računarske obuke', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Popravljati polomljene stvari ili opremu', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Birati filmove za program filmskog festivala', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Uređivati sportski časopis', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pisati scenarija za TV emisije', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Upravljati radom sportskog kluba', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Upravljati motornim vozilom', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Fizički štiti važne osobe (biti profesionalni telohranitelj)', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Saditi , brati i sušiti duvan', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pisati novinske članke o sportskim događajima', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Brinuti o nepokretnim ili starijim osobama', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Izdavati na šalteru razna dokumenta (uverenja, potvrde)', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Trenirati dečiji sportski tim', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Montirati i popravljati klima uređaje', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Određivati vrstu đubriva za pšenične useve', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Simultano prevoditi razgovore sa stranog jezika na srpski i obrnuto', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Sakupljati dokaze o delovanju organizovanih kriminalnih grupa', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Birati sportiste za državnu reprezentaciju', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Raditi na postavljanju vodovodnih instalacija', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Procenjivati vrednost umetničkih dela', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Voditi kozmetički salon', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Brinuti o ribi i ribljem mlađu u ribnjaku', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Voditi evidenciju o prijemu i izdavanju robe u magacinu ili skladištu', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Profesionalno se baviti sportom', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Spremati jela svetski poznatih kuhinja (italijanske, francuske, kineske...)', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Analizirati satelitske snimke za izradu vremenskih prognoza', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Režirati pozorišne predstave', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Brinuti o zdravlju domaćih životinja i kućnih ljubimaca', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Mešati razne vrste pića i praviti koktele', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pratiti određena lica radi sakupljanja obaveštajnih podataka', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Učiti strane jezike', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Raditi u institutu društvenih nauka', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Davati informacije kupcima o kvalitetu i cenama proizvoda', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Postavljati toplotnu i/ili zvučnu izolaciju u stanu', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Naplaćivati prodatu robu u robnoj kući', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Voditi zapisnik tokom poslovnog sastanka', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Osmišljavati izgled pakovanja za kafu', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Tapacirati stare kauče, stolice ili fotelje', '10');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Voditi TV emisiju o kulturi', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pomagati đacima da prevaziđu problem u učenju', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Baviti se naukom', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Oružano obezbeđivati važne objekte', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Raditi poslove inžinjera elektrotehnike', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Ugovarati nabavku robe od proizvođača', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Zasejavati poljoprivredne kulture (kukuruz, pšenicu, suncokret, šećernu repu...)', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Raditi u fabrici električnih uređaja', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Menjati novac po kursevima svetskih valuta', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Proučavati biljke i životinje u morima i okeanima', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Organizovati prijem i smeštaj gostiju u hotelima i motelima', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Ilustrovati naslovne strane knjiga i časopisa', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Profesionalno trenirati sportski tim', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Davati informacije o turističkoj ponudi', '12');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Ispitivati svedoke krivičnih dela', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Raditi u dečijem vrtiću ili obdaništu', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Proučavati nastanak, razvoj i kretanje nebeskih tela', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Učestvovati na međunarodnom filmskom festivalu', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pisati filmski scenario', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pružati prvu pomoć žrtvama nasilja', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Obrađivati zemljište pomoću poljoprivredne mehanizacije', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Primati i evidentirati molbe i žalbe građana', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Praviti zaštitu kompjuterskih programa od nelegalnog kopiranja', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Sakupljati pomoć za siromašne ljude', '8');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Osmišljavati izgled igračaka za decu', '4');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Komentarisati i prenositi sportske događaje na radiju ili televiziji', '11');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Gajiti vinograd', '9');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Saslušavati učesnike krivičnih dela', '2');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Smišljati baletska i scenska izvođenja (koreografije)', '5');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Voditi televizijsku emisiju', '6');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Kontrolisati rad električnih instalacija', '3');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Eksperimentisati sa lekovima za produžetak životnog veka ljudi', '7');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Pripremati dokumentaciju za poslovni sastanak', '1');
INSERT INTO POQUESTION(text, career_area_id) VALUES ('Voditi centar za brigu o deci ometenoj u razvoju', '8');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('1', '2');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('3', '4');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('5', '6');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('7', '8');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('9', '10');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('11', '12');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('13', '14');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('15', '16');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('17', '18');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('19', '20');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('21', '22');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('23', '24');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('25', '26');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('27', '28');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('29', '30');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('31', '32');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('33', '34');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('35', '36');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('37', '38');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('39', '40');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('41', '42');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('43', '44');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('45', '46');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('47', '48');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('49', '50');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('51', '52');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('53', '54');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('55', '56');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('57', '58');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('59', '60');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('61', '62');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('63', '64');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('65', '66');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('67', '68');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('69', '70');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('71', '72');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('73', '74');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('75', '76');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('77', '78');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('79', '80');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('81', '82');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('83', '84');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('85', '86');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('87', '88');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('89', '90');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('91', '92');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('93', '94');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('95', '96');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('97', '98');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('99', '100');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('101', '102');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('103', '104');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('105', '106');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('107', '108');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('109', '110');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('111', '112');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('113', '114');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('115', '116');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('117', '118');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('119', '120');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('121', '122');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('123', '124');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('125', '126');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('127', '128');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('129', '130');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('131', '132');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('133', '134');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('135', '136');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('137', '138');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('139', '140');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('141', '142');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('143', '144');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('145', '146');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('147', '148');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('149', '150');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('151', '152');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('153', '154');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('155', '156');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('157', '158');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('159', '160');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('161', '162');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('163', '164');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('165', '166');
INSERT INTO QUESTION_PAIR(question_a_id, question_b_id) VALUES ('167', '168');

