INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Meni su žurke život.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Osećam malu zabrinutost za druge.', 'AGREEABLENESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Uvek sam spreman.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Lako se nasekiram.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam bogat vokabular.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ne pricam mnogo.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Zainteresovan sam za ljude.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ostavljam svoje stvari za sobom.', 'CONSCIENTIOUSNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Uglavnom sam opušten.', 'NEUROTICISM', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Sa teškoćom shvatam apstraktne ideje.', 'OPENNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Osećam se prijatno u društvu.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Vređam ljude.', 'AGREEABLENESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Vodim računa o detaljima.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Brinem u vezi stvari.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam bujnu maštu.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ne volim da se ističem.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Saosećam sa tuđim osećanjima.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Neuredan sam.', 'CONSCIENTIOUSNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Retko osećam melanholiju.', 'NEUROTICISM', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam zainteresovan za apstraktne ideje.', 'OPENNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Započinjem konverzaciju.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam zainteresovan za probleme drugih ljudi.', 'AGREEABLENESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Rešavam svoje obaveze na vreme. ', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Lako se uznemirim.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam odlične ideje.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam pričljive prirode.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam meko srce.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Često zaboravljam da vratim stvari na svoje mesto.', 'CONSCIENTIOUSNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Lako se iznerviram.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam naročito maštovit.', 'OPENNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Pričam sa mnogo različitih ljudi na žurci.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Nisam zainteresovan za druge ljude.', 'AGREEABLENESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Volim red.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Često menjam raspoloženje.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Brzo shvatam stvari.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ne volim da privlačim pažnju na sebe.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Izdvajam vreme za druge.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Zabušavam.', 'CONSCIENTIOUSNESS', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Brzo menjam raspoloženje.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Koristim komplikovane reči.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Ne smeta mi kad sam u centru pažnje.', 'EXTROVERSION', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Imam osećaj empatije.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Pratim raspored.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Razdražljive sam prirode.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Periodično sagledavam stvari.', 'OPENNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Tih sam u prisustvu nepoznatih ljudi.', 'EXTROVERSION', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Činim da se drugi ljudi osećaju opušteno.', 'AGREEABLENESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Uživam u svom poslu.', 'CONSCIENTIOUSNESS', 'ADD');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Često se osećam melanholično.', 'NEUROTICISM', 'SUB');
INSERT INTO BIG_FIVE_QUESTION(text, trait, operation) VALUES ('Pun sam ideja.', 'OPENNESS', 'ADD');
