package bigFive;
import com.academic.adviser.model.BigFiveResults;
import com.academic.adviser.model.CareerArea;
import com.academic.adviser.constants.BigFiveTraitLevel;
import com.academic.adviser.drools.model.Traits;
import com.academic.adviser.drools.model.CareerAreas;
import java.util.ArrayList
import java.lang.Math;

global Double extroversionWeight;
global Double conscientiousnessWeight;
global Double neuroticismWeight;
global Double opennessWeight;
global Double agreeablenessWeight;

rule "High Extroversion"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(extroversion > Math.floor(20*extroversionWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.HIGH_EXTROVERSION); }
end

rule "Low Extroversion"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(extroversion <= Math.floor(20*extroversionWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.LOW_EXTROVERSION); }
end

rule "High Conscientiousness"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(conscientiousness > Math.floor(20*conscientiousnessWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.HIGH_CONSCIENTIOUSNESS); }
end

rule "Low Conscientiousness"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(conscientiousness <= Math.floor(20*conscientiousnessWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.LOW_CONSCIENTIOUSNESS); }
end

rule "High Neuroticism"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(neuroticism > Math.floor(20*neuroticismWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.HIGH_NEUROTICISM); }
end

rule "Low Neuroticism"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(neuroticism <= Math.floor(20*neuroticismWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.LOW_NEUROTICISM); }
end

rule "High Openness"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(openness > Math.floor(20*opennessWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.HIGH_OPENNESS); }
end

rule "Low Openness"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(openness <= Math.floor(20*opennessWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.LOW_OPENNESS); }
end

rule "High Agreeableness"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(agreeableness > Math.floor(20*agreeablenessWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.HIGH_AGREEABLENESS); }
end

rule "Low Agreeableness"
agenda-group "detect-personality"
lock-on-active true
when
    $r: BigFiveResults(agreeableness <= Math.floor(20*agreeablenessWeight))
    $t: Traits()
then
    modify($t) { addTrait(BigFiveTraitLevel.LOW_AGREEABLENESS); }
end

rule "Career Area Selection"
salience $rang
lock-on-active true
when
    $t: Traits($userTraits: traits)
    $c: CareerAreas(filled == false)
    $a: CareerArea($traits: traits, $rang: rang)
    Number($value: intValue >= 2) from accumulate(
        BigFiveTraitLevel($tm: this, this memberOf $userTraits) from $traits,
        count($tm)
    )
then
    modify($c) { addCareerArea($a) }
end

rule "Get "
salience 1
lock-on-active true
when
    $c: CareerAreas(careerAreas.size() == 0)
    $all: ArrayList() from collect( CareerArea() )
then
    modify($c) { addAllAreas($all) }
end