package bigFive;
import com.academic.adviser.dto.BigFiveAnswerDTO;
import com.academic.adviser.model.BigFiveResults;

rule "BigFive Question_50"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 50)
    $r: BigFiveResults()
then
    modify ($r) { addOpenness($p.getScore()) };
end

rule "BigFive Question_49"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 49)
    $r: BigFiveResults()
then
    modify ($r) { subNeuroticism($p.getScore()) };
end

rule "BigFive Question_48"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 48)
    $r: BigFiveResults()
then
    modify ($r) { addConscientiousness($p.getScore()) };
end

rule "BigFive Question_47"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 47)
    $r: BigFiveResults()
then
    modify ($r) { addAgreeableness($p.getScore()) };
end

rule "BigFive Question_46"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 46)
    $r: BigFiveResults()
then
    modify ($r) { subExtroversion($p.getScore()) };
end

rule "BigFive Question_45"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 45)
    $r: BigFiveResults()
then
    modify ($r) { addOpenness($p.getScore()) };
end

rule "BigFive Question_44"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 44)
    $r: BigFiveResults()
then
    modify ($r) { subNeuroticism($p.getScore()) };
end

rule "BigFive Question_43"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 43)
    $r: BigFiveResults()
then
    modify ($r) { addConscientiousness($p.getScore()) };
end

rule "BigFive Question_42"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 42)
    $r: BigFiveResults()
then
    modify ($r) { addAgreeableness($p.getScore()) };
end

rule "BigFive Question_41"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 41)
    $r: BigFiveResults()
then
    modify ($r) { addExtroversion($p.getScore()) };
end

rule "BigFive Question_40"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 40)
    $r: BigFiveResults()
then
    modify ($r) { addOpenness($p.getScore()) };
end

rule "BigFive Question_39"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 39)
    $r: BigFiveResults()
then
    modify ($r) { subNeuroticism($p.getScore()) };
end

rule "BigFive Question_38"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 38)
    $r: BigFiveResults()
then
    modify ($r) { subConscientiousness($p.getScore()) };
end

rule "BigFive Question_37"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 37)
    $r: BigFiveResults()
then
    modify ($r) { addAgreeableness($p.getScore()) };
end

rule "BigFive Question_36"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 36)
    $r: BigFiveResults()
then
    modify ($r) { subExtroversion($p.getScore()) };
end

rule "BigFive Question_35"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 35)
    $r: BigFiveResults()
then
    modify ($r) { addOpenness($p.getScore()) };
end

rule "BigFive Question_34"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 34)
    $r: BigFiveResults()
then
    modify ($r) { subNeuroticism($p.getScore()) };
end

rule "BigFive Question_33"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 33)
    $r: BigFiveResults()
then
    modify ($r) { addConscientiousness($p.getScore()) };
end

rule "BigFive Question_32"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 32)
    $r: BigFiveResults()
then
    modify ($r) { subAgreeableness($p.getScore()) };
end

rule "BigFive Question_31"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 31)
    $r: BigFiveResults()
then
    modify ($r) { addExtroversion($p.getScore()) };
end

rule "BigFive Question_30"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 30)
    $r: BigFiveResults()
then
    modify ($r) { subOpenness($p.getScore()) };
end

rule "BigFive Question_29"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 29)
    $r: BigFiveResults()
then
    modify ($r) { subNeuroticism($p.getScore()) };
end

rule "BigFive Question_28"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 28)
    $r: BigFiveResults()
then
    modify ($r) { subConscientiousness($p.getScore()) };
end

rule "BigFive Question_27"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 27)
    $r: BigFiveResults()
then
    modify ($r) { addAgreeableness($p.getScore()) };
end

rule "BigFive Question_26"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 26)
    $r: BigFiveResults()
then
    modify ($r) { subExtroversion($p.getScore()) };
end

rule "BigFive Question_25"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 25)
    $r: BigFiveResults()
then
    modify ($r) { addOpenness($p.getScore()) };
end

rule "BigFive Question_24"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 24)
    $r: BigFiveResults()
then
    modify ($r) { subNeuroticism($p.getScore()) };
end

rule "BigFive Question_23"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 23)
    $r: BigFiveResults()
then
    modify ($r) { addConscientiousness($p.getScore()) };
end

rule "BigFive Question_22"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 22)
    $r: BigFiveResults()
then
    modify ($r) { subAgreeableness($p.getScore()) };
end

rule "BigFive Question_21"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 21)
    $r: BigFiveResults()
then
    modify ($r) { addExtroversion($p.getScore()) };
end

rule "BigFive Question_20"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 20)
    $r: BigFiveResults()
then
    modify ($r) { subOpenness($p.getScore()) };
end

rule "BigFive Question_19"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 19)
    $r: BigFiveResults()
then
    modify ($r) { addNeuroticism($p.getScore()) };
end

rule "BigFive Question_18"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 18)
    $r: BigFiveResults()
then
    modify ($r) { subConscientiousness($p.getScore()) };
end

rule "BigFive Question_17"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 17)
    $r: BigFiveResults()
then
    modify ($r) { addAgreeableness($p.getScore()) };
end

rule "BigFive Question_16"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 16)
    $r: BigFiveResults()
then
    modify ($r) { subExtroversion($p.getScore()) };
end

rule "BigFive Question_15"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 15)
    $r: BigFiveResults()
then
    modify ($r) { addOpenness($p.getScore()) };
end

rule "BigFive Question_14"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 14)
    $r: BigFiveResults()
then
    modify ($r) { subNeuroticism($p.getScore()) };
end

rule "BigFive Question_13"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 13)
    $r: BigFiveResults()
then
    modify ($r) { addConscientiousness($p.getScore()) };
end

rule "BigFive Question_12"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 12)
    $r: BigFiveResults()
then
    modify ($r) { subAgreeableness($p.getScore()) };
end

rule "BigFive Question_11"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 11)
    $r: BigFiveResults()
then
    modify ($r) { addExtroversion($p.getScore()) };
end

rule "BigFive Question_10"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 10)
    $r: BigFiveResults()
then
    modify ($r) { subOpenness($p.getScore()) };
end

rule "BigFive Question_9"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 9)
    $r: BigFiveResults()
then
    modify ($r) { addNeuroticism($p.getScore()) };
end

rule "BigFive Question_8"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 8)
    $r: BigFiveResults()
then
    modify ($r) { subConscientiousness($p.getScore()) };
end

rule "BigFive Question_7"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 7)
    $r: BigFiveResults()
then
    modify ($r) { addAgreeableness($p.getScore()) };
end

rule "BigFive Question_6"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 6)
    $r: BigFiveResults()
then
    modify ($r) { subExtroversion($p.getScore()) };
end

rule "BigFive Question_5"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 5)
    $r: BigFiveResults()
then
    modify ($r) { addOpenness($p.getScore()) };
end

rule "BigFive Question_4"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 4)
    $r: BigFiveResults()
then
    modify ($r) { subNeuroticism($p.getScore()) };
end

rule "BigFive Question_3"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 3)
    $r: BigFiveResults()
then
    modify ($r) { addConscientiousness($p.getScore()) };
end

rule "BigFive Question_2"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 2)
    $r: BigFiveResults()
then
    modify ($r) { subAgreeableness($p.getScore()) };
end

rule "BigFive Question_1"
agenda-group "big-five-questions"
lock-on-active true
when
    $p: BigFiveAnswerDTO(id == 1)
    $r: BigFiveResults()
then
    modify ($r) { addExtroversion($p.getScore()) };
end


